---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: osr-f-angular
  namespace: osr
  labels:
    app: osr-f-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osr-f-angular
  template:
    metadata:
      labels:
        app: osr-f-angular
    spec:
      containers:
        - name: osr-f-angular
          image: 'registry.mpwt.gov.kh:4000/sovichea10/osr-f-angular:${current_tag}'
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: 'Asia/Phnom_Penh'
          resources: {}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      hostNetwork: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: private-registry

---
kind: Service
apiVersion: v1
metadata:
  name: osr-f-angular
  namespace: osr
spec:
  selector:
    app: osr-f-angular
  type: NodePort
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30078
